license = "MIT"
# issueTrackerURL = "https://github.com/CompactMods/Gander/issues"
issueTrackerURL = "https://discord.gg/Y5QhUWxQdq"
modLoader = "javafml"
loaderVersion = "[3,)"

[[mods]]
    modId = "gander"
    displayName = "Gander - TestMod"
    version = "${MOD_VERSION}"
    authors = "RobotGryphon, FiniteReality, ApexModder"
    description = "Take a peek at the world and what it has to offer!"

    [[accessTransformers]]
        file = "META-INF/accesstransformer.cfg"

    [[dependencies.gander]]
        modId = "minecraft"
        type = "required"
        versionRange = "[1.20.6,1.21)"
        ordering = "NONE"
        side = "BOTH"
    [[dependencies.gander]]
        modId = "neoforge"
        type = "required"
        versionRange = "[20.6,21.0)"
        ordering = "NONE"
        side = "BOTH"
