modLoader="javafml"
loaderVersion="${loader_version}" #mandatory
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Gander Test Mod"
authors="You!"
description='''
It's testing time
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="gander"
type="required"
versionRange="${mod_version}"
ordering="AFTER"
side="CLIENT"
