modLoader="javafml"
loaderVersion="${loader_version}" #mandatory
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Gander"
authors="RobotGryphon, FiniteReality"
description='''
Take a peek at the world and see what it has to offer!
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
