name: Continuous Integration

env:
    GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
    workflow_dispatch:

    push:
        paths-ignore:
            - "README.md"
            - "LICENSE"
            - ".github/**/*"
            - "**/*.gradle.kts"
            - "**/gradle.properties"

jobs:
    vars:
        name: Get Variables
        runs-on: ubuntu-22.04
        outputs:
            version: ${{steps.version.outputs.version}}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 150
                    fetch-tags: true

            -   name: Version
                id: version
                uses: paulhatch/semantic-version@v5.4.0
                with:
                    version_format: "${major}.${minor}.${patch}"
                    search_commit_body: true
                    bump_each_commit: true

    publish:
        name: Publish Code as Github Package - ${{ inputs.version }}
        needs: [ vars ]
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: true

            -   name: Set up JDK
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: 17

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Publish
                run: ./gradlew :publish
                env:
                    VERSION: ${{ inputs.version }}
                    GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
